#!/bin/sh

ffmpeg -y -i $1 -vf "fps=15,scale=512:-1:flags=lanczos,palettegen" /tmp/$1
ffmpeg -i $1 -i /tmp/$1 -filter_complex "fps=15,scale=512:-1:flags=lanczos[x];[x][1:v]paletteuse" $1.gif
rm /tmp/$1
